# Server
# ==================================================================

server.port: 8002

# Management
# ==================================================================

management:
  server.port: 8003

  endpoint.health.show-details: "always"
  endpoints.web.exposure.include: "*"

# Logging
# ==================================================================

logging.level:
  root: "warn"
  de.saschaufer: "info"

# RabbitMq
# ==================================================================

rabbitmq:
  host: "rabbitmq.server.lan"
  port: 5672
  management-port: 15672
  user: "develop"
  password: # changeit
  vhost: "develop"
  exchange: "message-broker"
  queue: "user"
  routingKey: "message-broker.user"
